---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nginx-1Mi
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
  volumeName: pv-nginx
  storageClassName: ""
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-nfs-example
  namespace: default
spec:
  containers:
    - image: nginx
      name: nginx
      ports:
        - containerPort: 80
          protocol: TCP
      volumeMounts:
        - mountPath: /var/www
          name: pvc-nginx-1Mi
  volumes:
    - name: pvc-nginx-1Mi
      persistentVolumeClaim:
        claimName: pvc-nginx-1Mi
